name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install Correct PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          extensions: mbstring, mysql, pdo_mysql, xml, zip
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --no-suggest
  
      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --seed --env=testing

      - name: Run PHPUnit tests
        run: php artisan test
